mimic_path = '/media/data3/biodataset/MIMIC_IV/MIMIC-IV-v3.0/physionet.org/files/mimiciv/3.0'
derive_path = '/media/data/huyennm/mimic-iv/mimic-derived/derived_database'
target_patients_path = '/media/data/huyennm/mimic-iv/mimiciv_data/get_patients/eligible_patients.csv'
derive_queries_path = '/media/data/huyennm/mimic-iv/mimic-derived/queries'
comorbidity_code_path = '/media/data/huyennm/mimic-iv/mimiciv_data/comorbidity/comorbidity_code'
mimiciv_data_path = '/media/data/huyennm/mimic-iv/mimiciv_data'
sorted_data_path = '/media/data/huyennm/mimic-iv/mimiciv_data/global_runs/sorted_data'
final_data_path = '/media/data/huyennm/mimic-iv/mimiciv_data/final_data.csv'